services:
  - type: web
    name: wordaholic
    env: node
    plan: free
    buildCommand: npm install && npm run build:full
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000