/**
 * Auto-generated by scripts/embed-admin-password.js — do not edit by hand.
 * Source: default
 */
export const ADMIN_PASSWORD_HASH = '3c9ff67ab650bc854b145c690b52efc42ed356151a181513b64f2e799e24ec5f';
export const ADMIN_PASSWORD_SOURCE = 'default';
